### ISSUE TITLE
Iframe Messes with the preview

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#142]
So I added the embed code manually:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/TNav0EoeNGI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

and it the preview below doesn't show anything after the video.

**Comment by tiotdev** [comment]
No HTML pasted into the easy editor works, since it is not a HTML editor. Since developing our own editor is too complicated/time intensive, we will have to life with the editor until there is a better working alternative, like editor.js but without the bugs. Closing in favor of https://github.com/travelfeed-io/travelfeed-io/issues/67
